baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Reveal Hugo Presentation'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
codeFences = false

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "blood"
#theme = "night"
highlight_theme = "tokyo-night-dark"
#highlight_theme = "atom-one-dark-reasonable"
#transition = "convex"
slide_number = true
